#!/usr/bin/env bash
# shellcheck disable=SC2016  # Backticks in single quotes are literal strings
# antcrate :: lib/obsidian.sh — Obsidian vault mirroring
#
# Mirrors AntCrate registry and project metadata into an Obsidian vault as
# read-only markdown files. One-way only: never modifies the registry or
# project state based on vault contents.
#
# Sourced by wrapper. Depends on registry.sh, log.sh.

: "${ANTCRATE_HOME:=$HOME/.antcrate}"
: "${ANTCRATE_OBSIDIAN_VAULT:=}"

# ---------- Public API ----------

# ac_obsidian_mirror [project] [--with-docs]
# Mirror registry and optionally a specific project into the Obsidian vault.
# If [project] is given, only mirror that one (must be registered).
# Otherwise, mirror all registered projects.
#
# Optional: [--with-docs] — also copy each project's *.md files as vault notes.
#
# Returns 0 on success; 2 on config/validation error.
ac_obsidian_mirror() {
    local project_filter="${1:-}"
    local with_docs=0

    # Parse optional flags (must come after project name)
    if [[ "$#" -ge 2 && "$2" == "--with-docs" ]]; then
        with_docs=1
    fi

    # Validate vault is configured
    if [[ -z "${ANTCRATE_OBSIDIAN_VAULT}" ]]; then
        ac_error "obsidian-mirror: ANTCRATE_OBSIDIAN_VAULT not set"
        ac_error "  hint: set ANTCRATE_OBSIDIAN_VAULT=<vault-path> in ~/.antcrate/config"
        return 2
    fi

    # Validate vault exists
    if [[ ! -d "${ANTCRATE_OBSIDIAN_VAULT}" ]]; then
        ac_error "obsidian-mirror: vault directory does not exist: ${ANTCRATE_OBSIDIAN_VAULT}"
        return 2
    fi

    # If a specific project is requested, verify it exists
    if [[ -n "$project_filter" ]]; then
        if ! ac_registry_has "$project_filter"; then
            ac_error "obsidian-mirror: unknown project '$project_filter'"
            return 2
        fi
    fi

    local base="${ANTCRATE_OBSIDIAN_VAULT}/AntCrate"
    mkdir -p "$base/projects"

    # Write registry note
    _ac_obsidian_write_registry "$base" || true

    # Determine projects to mirror
    local projects_to_mirror=()
    if [[ -n "$project_filter" ]]; then
        projects_to_mirror=("$project_filter")
    else
        mapfile -t projects_to_mirror < <(ac_registry_list | sort || true)
    fi

    # Write project notes
    local written=0
    local unchanged=0
    if [[ ${#projects_to_mirror[@]} -gt 0 ]]; then
        for proj in "${projects_to_mirror[@]}"; do
            local proj_path
            proj_path=$(ac_registry_get "$proj" path)
            if [[ ! -d "$proj_path" ]]; then
                ac_warn "obsidian-mirror: skipping '$proj' — path does not exist: $proj_path"
                continue
            fi
            if _ac_obsidian_write_project "$base" "$proj" "$with_docs" || true; then
                (( written++ ))
            else
                (( unchanged++ ))
            fi
            if [[ "$with_docs" == "1" ]]; then
                _ac_obsidian_copy_project_docs "$base" "$proj" || true
            fi
        done || true
    fi

    local total=$(( written + unchanged ))
    ac_info "obsidian-mirror: mirrored $total project(s) to $base ($written written, $unchanged unchanged)" || true
    return 0
}

# ---------- Internal ----------

# _ac_obsidian_find_project_docs <project_path>
# Find all *.md files in project, pruning standard exclusion dirs.
# Outputs file paths one per line, sorted.
_ac_obsidian_find_project_docs() {
    local path="$1"
    find "$path" -type f -name '*.md' \
        -not -path '*/.git/*' \
        -not -path '*/node_modules/*' \
        -not -path '*/target/*' \
        -not -path '*/dist/*' \
        -not -path '*/build/*' \
        -not -path '*/__pycache__/*' \
        -not -path '*/.next/*' \
        -not -path '*/.cache/*' \
        -not -path '*/.svelte-kit/*' \
        | sort
}

# _ac_obsidian_write_registry <base_dir>
# Write $base_dir/Registry.md with registry graph and project list.
# Skips ghost entries (registry entries whose path no longer exists).
# Idempotent via cmp check.
_ac_obsidian_write_registry() {
    local base="$1"
    local out="$base/Registry.md"
    local tmp; tmp=$(mktemp)

    {
        printf '> [!note] Generated by `antcrate --obsidian-mirror` — do not edit.\n'
        printf '\n'
        printf '# AntCrate Registry\n'
        printf '\n'

        # Registry graph (if available)
        if [[ -f "$ANTCRATE_HOME/registry.mmd" ]]; then
            printf '```mermaid\n'
            cat "$ANTCRATE_HOME/registry.mmd"
            printf '\n```\n'
        else
            printf '_(no registry.mmd — run `antcrate --registry-diagram`)_\n'
        fi

        printf '\n## Projects\n'
        printf '\n'

        # Project list (skip ghosts)
        ac_registry_list | sort | while read -r proj; do
            local proj_path
            proj_path=$(ac_registry_get "$proj" path)
            [[ -d "$proj_path" ]] && printf -- '- [[%s]]\n' "$proj"
        done
    } > "$tmp"

    # Write only if changed
    if [[ ! -f "$out" ]] || ! cmp -s "$tmp" "$out"; then
        mv "$tmp" "$out"
        return 0
    else
        rm -f "$tmp"
        return 1
    fi
}

# _ac_obsidian_write_project <base_dir> <project_name> [with_docs]
# Write $base_dir/projects/<project_name>.md with project metadata and notes.
# If with_docs is 1, also copy project's *.md files as vault notes and add
# ## Documents section listing them.
# Returns 0 if written, 1 if unchanged (via cmp).
_ac_obsidian_write_project() {
    local base="$1"
    local proj="$2"
    local with_docs="${3:-0}"
    local out="$base/projects/${proj}.md"
    local tmp; tmp=$(mktemp)

    # Gather project metadata
    local path; path=$(ac_registry_get "$proj" path)
    local domain; domain=$(ac_registry_get "$proj" parent)
    local git_remote; git_remote=$(ac_registry_get "$proj" git_remote)
    [[ -z "$git_remote" ]] && git_remote="(none)"

    # Count backups (using bash globbing instead of find)
    local backup_count=0
    local backup_dir="$ANTCRATE_HOME/backups/$proj"
    if [[ -d "$backup_dir" ]]; then
        local -a backups
        backups=( "$backup_dir"/*.tar.gz )
        [[ -f "${backups[0]}" ]] && backup_count=${#backups[@]}
    fi

    {
        # YAML frontmatter MUST be the first bytes of the file or Obsidian
        # parses it as a horizontal rule instead of queryable Properties.
        printf '%s\n' '---'
        printf 'antcrate-project: %s\n' "$proj"
        printf 'domain: %s\n' "$domain"
        printf 'git_remote: %s\n' "$git_remote"
        printf 'path: %s\n' "$path"
        printf 'backups: %d\n' "$backup_count"
        printf '%s\n' '---'
        printf '\n'
        printf '> [!note] Generated by `antcrate --obsidian-mirror` — do not edit.\n'
        printf '\n'
        printf '# %s\n' "$proj"
        printf '\n'

        # Tree diagram (if available)
        local tree_mmd="$path/docs/diagrams/tree.mmd"
        if [[ -f "$tree_mmd" ]]; then
            printf '## Tree\n'
            printf '\n'
            printf '```mermaid\n'
            cat "$tree_mmd"
            printf '\n```\n'
            printf '\n'
        fi

        # Documents section (only if --with-docs)
        if [[ "$with_docs" == "1" ]]; then
            local doc_files=()
            mapfile -t doc_files < <(_ac_obsidian_find_project_docs "$path")
            if [[ ${#doc_files[@]} -gt 0 ]]; then
                printf '## Documents\n'
                printf '\n'
                for doc in "${doc_files[@]}"; do
                    local rel_doc="${doc#"$path"/}"
                    local doc_name="${rel_doc%.md}"
                    printf -- '- [[AntCrate/projects/%s/%s|%s]]\n' "$proj" "$doc_name" "$rel_doc"
                done
                printf '\n'
            fi
        fi

        # Linked nodes
        printf '## Linked\n'
        printf '\n'
        local linked_nodes
        mapfile -t linked_nodes < <(ac_registry_get "$proj" linked_nodes)
        if (( ${#linked_nodes[@]} > 0 )); then
            printf '%s\n' "${linked_nodes[@]}" | sort | while read -r linked; do
                printf -- '- [[%s]]\n' "$linked"
            done
        else
            printf '_(none)_\n'
        fi
        printf '\n'

        # Recent ledger
        printf '## Ledger (recent)\n'
        printf '\n'
        local ledger="$path/ledger.md"
        if [[ -f "$ledger" ]]; then
            printf '```\n'
            tail -n 5 "$ledger" 2>/dev/null || true
            printf '\n```\n'
        else
            printf '_(no ledger)_\n'
        fi
    } > "$tmp"

    # Write only if changed
    if [[ ! -f "$out" ]] || ! cmp -s "$tmp" "$out"; then
        mv "$tmp" "$out"
        return 0
    else
        rm -f "$tmp"
        return 1
    fi
}

# _ac_obsidian_copy_project_docs <base_dir> <project_name>
# Copy all *.md files from the project into the vault with proper headers.
# Creates subdirectories as needed. Idempotent via cmp.
_ac_obsidian_copy_project_docs() {
    local base="$1"
    local proj="$2"
    local path; path=$(ac_registry_get "$proj" path)

    local doc_files=()
    mapfile -t doc_files < <(_ac_obsidian_find_project_docs "$path")

    for src in "${doc_files[@]}"; do
        local rel="${src#"$path"/}"
        local out="$base/projects/$proj/$rel"
        local out_dir; out_dir=$(dirname "$out")
        mkdir -p "$out_dir"

        local tmp; tmp=$(mktemp)
        {
            printf '> [!note] Mirrored by `antcrate --obsidian-mirror --with-docs` from %s — do not edit (edit the source).\n' "$rel"
            printf '\n'
            cat "$src"
        } > "$tmp"

        if [[ ! -f "$out" ]] || ! cmp -s "$tmp" "$out"; then
            mv "$tmp" "$out"
        else
            rm -f "$tmp"
        fi
    done
}

# ac_obsidian_auto_regen <project>
# Opt-in auto-regeneration of Obsidian mirror after mutating actions.
# Only runs if ANTCRATE_OBSIDIAN_AUTO == 1 AND vault is configured/exists.
# Metadata-only mode (no --with-docs). Errors are swallowed so this can
# never block the triggering action.
ac_obsidian_auto_regen() {
    local project="${1:-}"

    [[ "${ANTCRATE_OBSIDIAN_AUTO:-0}" == "1" ]] || return 0
    [[ -n "${ANTCRATE_OBSIDIAN_VAULT}" ]] || return 0
    [[ -d "${ANTCRATE_OBSIDIAN_VAULT}" ]] || return 0

    ac_obsidian_mirror "$project" || true
    return 0
}
